# consul
services:
  consul-server-1:
    image: hashicorp/consul:latest
    entrypoint: /entrypoint.sh
    environment:
      ARG_CONSUL_RETRY_JOIN: consul-server-2 consul-server-3
    volumes:
      - consul-server-1-vol:/consul/data
      - ./entrypoint.sh:/entrypoint.sh:ro
    restart: unless-stopped

  consul-server-2:
    image: hashicorp/consul:latest
    entrypoint: /entrypoint.sh
    environment:
      ARG_CONSUL_RETRY_JOIN: consul-server-1 consul-server-3
    volumes:
      - consul-server-2-vol:/consul/data
      - ./entrypoint.sh:/entrypoint.sh:ro
    restart: unless-stopped

  consul-server-3:
    image: hashicorp/consul:latest
    entrypoint: /entrypoint.sh
    environment:
      ARG_CONSUL_RETRY_JOIN: consul-server-1 consul-server-2
    volumes:
      - consul-server-3-vol:/consul/data
      - ./entrypoint.sh:/entrypoint.sh:ro
    restart: unless-stopped

  consul-client:
    image: hashicorp/consul:latest
    command:
      - agent
      - -config-file=/consul/config/client-config.json
    ports:
      - "8500:8500" # HTTP API & UI
      - "8600:8600/udp" # DNS
    volumes:
      - consul-client-vol:/consul/data
      - ./client-config.json:/consul/config/client-config.json:ro
    restart: unless-stopped
    depends_on:
      - consul-server-1
      - consul-server-2
      - consul-server-3

networks:
  default:
    name: shared-net
    external: true
    driver: bridge

volumes:
  consul-server-1-vol:
  consul-server-2-vol:
  consul-server-3-vol:
  consul-client-vol:
