static_resources:
  listeners:
  - name: redis_sentinel_listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 26379
    filter_chains:
    - filters:
      - name: envoy.filters.network.tcp_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          stat_prefix: redis_sentinel_tcp
          cluster: redis_sentinel_cluster
          access_log:
          - name: envoy.access_loggers.stdout
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog

  clusters:
  - name: redis_sentinel_cluster
    connect_timeout: 3s
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: redis_sentinel_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: redis-sentinel-1
                port_value: 26379
        - endpoint:
            address:
              socket_address:
                address: redis-sentinel-2
                port_value: 26379
        - endpoint:
            address:
              socket_address:
                address: redis-sentinel-3
                port_value: 26379
    health_checks:
    - timeout: 2s
      interval: 5s
      unhealthy_threshold: 2
      healthy_threshold: 2
      tcp_health_check: {}

admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901